### ISSUE TITLE
error in tutorial page

### ISSUE THREAD

**Issue by jox81** [angular-examples/toh-5#1]
hi, 

I'm trying to follow the tutorial page https://angular.io/docs/dart/latest/tutorial/toh-pt5.html and some code isn't correctly written. 

There's a lot of error code like : 
`BAD FILENAME: ../../../_fragments/toh-5/dart/lib/dashboard_component-gotoDetail.dart.md   Current path: docs,dart,latest,tutorial,toh-pt5 PathToDocs: ../../../`

So, I've decided to check the code here but i've got a problem with my history back which gives me an error like this :
`>EXCEPTION: 
  EXCEPTION: 
    (anonymous function)	
  STACKTRACE:
    (anonymous function)	
  dart:async                                               _BroadcastStreamController.addError
package:angular2/src/facade/async.dart 29:17             EventEmitter.addError
package:angular2/src/router/router.dart 255:14           Router._emitNavigationFail
package:angular2/src/router/router.dart 466:16           RootRouter.RootRouter.<fn>.<fn>
package:stack_trace                                      StackZoneSpecification.registerUnaryCallback.<fn>
package:angular2/src/core/zone/ng_zone_impl.dart 153:40  NgZoneImpl._runUnary.<fn>
dart:async                                               _ZoneDelegate.run
package:angular2/src/core/zone/ng_zone_impl.dart 146:21  NgZoneImpl._run
package:angular2/src/core/zone/ng_zone_impl.dart 153:7   NgZoneImpl._runUnary
dart:async                                               _Future._asyncComplete.<fn>
package:angular2/src/core/zone/ng_zone_impl.dart 167:11  NgZoneImpl._scheduleMicrotask.<fn>
dart:async                                               _ZoneDelegate.run
package:angular2/src/core/zone/ng_zone_impl.dart 146:21  NgZoneImpl._run
`

Is there a problem with the currect router functions ?

Thx

**Comment by kwalrath** [comment]
Yikes. @chalin can you look into this?

**Comment by chalin** [comment]
The `BAD FILENAME` issue is being tracked via https://github.com/angular/angular.io/issues/2774.

**Comment by chalin** [comment]
The full issue in now being tracked via https://github.com/angular/angular.io/issues/2775.

@jox81 - thanks for the report, but next time, please open the issue directly over angular/angular.io.

**Comment by jox81** [comment]
Ok I'll do that, thank you for the report !
