### ISSUE TITLE
Refreshing page on any of the routes give 404

### ISSUE THREAD

**Issue by tanelainla** [angular-examples/toh-5#5]
Did the tutorial today and was not able to get it working properly. When I debug with Dartium then page loads and I can click around router links, but refresh does not work. Now I also cloned your repository and run it with and without Webstorm/Dartium (just `pub serve` and Chrome). Still whenever I press F5 in the browser then app gets 404 and page breaks.

Using Webstorm and Dartium (First I run it and it works. Then I hit refresh and it breaks and after that it does not even load after I re-run the app from Webstrom (I just see "Loading..." HTML template). I have to close Dartium and do a full clean build for the project to get one working cycle again... This kind of debug cycles are tedious...):

![untitled](https://cloud.githubusercontent.com/assets/266139/26125430/ce622a7e-3a8a-11e7-9a78-c66361fcec25.gif)

With `pub serve` in Chrome:

<img width="507" alt="screen shot 2017-05-16 at 10 23 37 pm" src="https://cloud.githubusercontent.com/assets/266139/26124302/ab9509de-3a86-11e7-82f5-da157193899e.png">

**Comment by tanelainla** [comment]
Ok. Now I got it working from command line with `pub serve` and Chrome, but it's still not working with Dartium and Webstorm.

I modified `main.dart`:
```
void main() {
  bootstrap(AppComponent,[
    ROUTER_PROVIDERS,
    provide(LocationStrategy, useClass: HashLocationStrategy)
  ]);
}
```
I wonder if this is some kind of Webstorm/Dartium issue?

**Comment by kwalrath** [comment]
@chalin should I move this to webdev?

**Comment by chalin** [comment]
This is being tracked via https://github.com/dart-lang/site-webdev/issues/252. Thanks for commenting there as well.
